---
apiVersion: v1
data:
  .{{ docker_registry_secret_type }}: {{ docker_registry_secret }}
kind: Secret
metadata:
  name: {{ docker_registry_secret_name_prefix }}-registrysecret
  namespace: default
type: kubernetes.io/{{ docker_registry_secret_type }}
---
apiVersion: v1
kind: Secret
metadata:
  name: @= project_name =@-secret-envs
  namespace: default
type: Opaque
data:
  POSTGRES_APP_DATABASE_PASSWORD: "{{ @= project_name_with_underscore =@_db_password | b64encode }}"
  POSTGRES_EVENTS_DATABASE_PASSWORD: "{{ events_db_password | b64encode }}"
  AWS_ACCESS_KEY_ID: "{{ django_apps_aws_access_key | b64encode }}"
  AWS_SECRET_ACCESS_KEY: "{{ django_apps_aws_secret_key | b64encode }}"
---