apiVersion: v1
kind: Service
metadata:
  name: @= project_name =@
  labels:
    app: @= project_name =@
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: @= project_name =@
